### ISSUE TITLE
web-types path in package.json generated invalid on Windows

### ISSUE THREAD

**Issue by JanThiel** [break-stuff/cem-plugin-jet-brains-ide-integration#1]
Hey there,

thank you very much for this nice and handy plugin.
It works very well in general yet we found this particular issue.

After running the plugin as part of the `cem analyze --litelement` on Windows, the `package.json` contains this path:

`  "web-types": "dist\\web-types.json", `

This is obvious to the nature of `path` generationg OS aware paths. Yet in this case this is misleading as it generates Windows paths into the package.json which only expects unix paths where the seperator is `/`.

This is the relevant code:

https://github.com/break-stuff/cem-plugin-jet-brains-ide-integration/blob/8b8e86a73ea3e7dc369a68cda985ea71b0bee3c7/src/web-type-generator/generator.ts#L359-L362

I guess switching to a _dumb_ `outputPathElements.join( '/' ) ` should fix this :-)

All the best!

Jan

**Comment by break-stuff** [comment]
Thank you very much for reaching out and for reporting the issue! I will get that patched.

**Comment by break-stuff** [comment]
The patch has been deployed. Let me know if you run into any other issues. Thanks!
