### ISSUE TITLE
Source code version not representative to npm package

### ISSUE THREAD

**Issue by basvanrooten** [break-stuff/cem-plugin-jet-brains-ide-integration#6]
Hi,
First of all I would like to thank you for all the work you're doing on the CEM integrations for different IDEs. Much appreciated!

I am wondering why there is a disconnect between the versioning in NPM and in this repo. The repo URL on NPM links to this repository, but on NPM it states that the version is `1.2.1`, while the package.json mentions `1.0.0-beta.2`. Besides, the latest activity on this repo is aug 7th, but the last npm deployment was aug 11th.

Has this project become closed source? Or am I missing something?

**Comment by break-stuff** [comment]
This project is deprecated and is replaced with [this project](https://github.com/break-stuff/cem-tools/tree/main/packages/jet-brains-integration). I went ahead and updated the URLs to reference the new project. Thank you for catching this!

**Comment by basvanrooten** [comment]
Thank you, the references on NPM to the new repo look fine now. As a consideration, maybe also mark this project as archived?

**Comment by break-stuff** [comment]
Will do!
